.PHONY: clean

clean:
	rm -f *.aux
	rm -f *.bbl
	rm -f *.blg
	rm -f *.fdb_latexmk
	rm -f *.fls
	rm -f *.log
	rm -f *.synctex.gz
	rm -f *.out
	rm -f *.bcf
	rm -f *.run.xml
	rm -f *.toc
	rm -f *.nav
	rm -f *.snm
	rm -f *.vrb
